FROM php:7.4-apache

RUN apt-get update && \
    apt-get install -y \
        libcurl4-openssl-dev \
        libssl-dev \
        libzip-dev \
        unzip \
        curl && \
    docker-php-ext-install mysqli pdo pdo_mysql && \
    docker-php-ext-enable mysqli pdo pdo_mysql && \
    a2enmod rewrite && \
    service apache2 restart
